# Generated by Django 2.2.7 on 2020-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=300)),
            ],
        ),
    ]
