# Generated by Django 2.2.7 on 2020-03-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200301_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
