# Generated by Django 2.2.7 on 2020-03-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200301_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(blank=True),
        ),
    ]
